### ISSUE TITLE
Feat: Post Detail 컴포넌트 구현

### ISSUE THREAD

**Issue by rlacksals96** [prgrms-web-devcourse/Team_Ahpuh_Surf_FE#70]
## 👀 기능 설명
*  Post Detail 컴포넌트 구현

![스크린샷 2021-12-04 오후 2 25 28](https://user-images.githubusercontent.com/19158155/144698443-411f2217-5055-47c0-9d9e-2894d1e705ed.png)

## 📆 예상 작업 기간
2 man day

**Comment by Jeong-jeong** [comment]
와아우
